# Generated by Django 3.1 on 2021-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210319_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, null=True)),
                ('Phone', models.CharField(max_length=14, null=True)),
                ('Email', models.CharField(max_length=70, null=True)),
                ('Message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
