# Generated by Django 3.1 on 2021-03-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Comment',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='line2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='line3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='line4',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
