# Generated by Django 3.1 on 2021-03-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210324_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Standard',
            field=models.IntegerField(default=0),
        ),
    ]
