# Generated by Django 3.1 on 2021-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210330_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Standard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
